version: "3.9"
services:
 bot:
  build: .
  restart: always
  volumes:
   - '/var/log:/var/log'
  environment:
   - DISCORD_BOTKEY=${DISCORD_BOTKEY}
 db:
  image: redis:7.2.1-alpine
  restart: always
  volumes:
   - '/var/opt/osrs_games_db:/data'
